# Generated by Django 6.1 on 2026-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True)),
                ('hero_title', models.CharField(max_length=300)),
                ('hero_description', models.TextField()),
                ('hero_image', models.URLField(blank=True)),
                ('about_title', models.CharField(blank=True, max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('about_image', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('maps_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
